import { useUser } from '@/context/user';
import { supabase } from '@/utils/supabaseClient';
import type { NextPage, NextPageContext } from 'next';
import Head from 'next/head';
import Link from 'next/link';

const Home: NextPage = ({ notes }) => {
  const { user, logout } = useUser();
  // console.log(user);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col justify-center items-center h-screen p-2">
        <header className="flex flex-col items-end w-full">
          {user ? (
            <button
              className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2"
              onClick={logout}
            >
              Logout
            </button>
          ) : (
            <Link href="/login">
              <button className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:ring-2">
                Login
              </button>
            </Link>
          )}
        </header>
        <main className="flex flex-1 flex-col justify-center items-center py-20">
          {notes.map((note) => (
            <div key={note.id} className="flex flex-col items-center">
              <Link key={note.id} href={`/note/${note.id}`}>
                <a className="p-8 h-40 mb-4 rounder shadow text-xl flex">
                  {note.title}
                </a>
              </Link>
            </div>
          ))}
        </main>
      </div>
    </>
  );
};

export default Home;

export const getStaticProps = async (ctx: NextPageContext) => {
  const { data: notes } = await supabase.from('notes').select('*');

  return {
    props: {
      notes,
    },
  };
};
